### ISSUE TITLE
Slepen naar componentengereedschapskist verwijdert de componenten niet

### ISSUE THREAD

**Issue by usadson** [Murkfloostick/Peach#49]
## Verwachte uitkomst
Het element wordt verwijderd uit het scherm.

## Daadwerkelijke uitkomst
Het element verstopt zich achter het paneel.

## Mogelijke oplossing
Als de cursor wordt gesleept boven het componentenpaneel dan krijgt de cursor een X om aan te duiden dat het element verwijderd kan worden. Als de muis dan losgelaten wordt verdwijnt het element.

**Comment by Labhatorian** [comment]
Niet mogelijk omdat dragpaneel prioriteit krijgt en waardoor de drag and drop functies niet worden opgeroepen
