### ISSUE TITLE
Geen Euro-teken op Windows door encoding

### ISSUE THREAD

**Issue by Labhatorian** [Murkfloostick/Peach#60]
![afbeelding](https://user-images.githubusercontent.com/16213031/169572404-f7ebd0d9-722c-4f6c-a289-593567426dea.png)

**Comment by usadson** [comment]
Oei! Dat is niet de bedoeling inderdaad
Ik heb dit gedaan om de getallen te laten printen 100.002,00 ipv 100,002.00
Nederlands stond er niet zo tussen, dus die leek goed te werken.
Op Linux werkte hij wel goed 🙃

**Comment by usadson** [comment]
Kan iemand die Windows gebruikt hiernaar kijken?

**Comment by Labhatorian** [comment]
Ik zie geen verschil

**Comment by usadson** [comment]
Font gewijzigd, misschien lag het daaraan?

**Comment by Labhatorian** [comment]
Encoding staat op windows-1252, zal op UTF-8 moeten maar lukt niet met `-Dfile.encoding=UTF-8` arg
