### ISSUE TITLE
Componenten worden niet verwijderd op niet-Windows platformen

### ISSUE THREAD

**Issue by frepds** [Murkfloostick/Peach#66]
Zie titel, op windows werkt het wel, niet op MAC.

**Comment by Labhatorian** [comment]
Kan iemand met een Mac kijken waar dit fout gaat? Ff debuggen bij `verwijderComponent()` in `DPWorkPanel` en dan graag kijken wat de variabelen `target` en `PC` zijn

**Comment by usadson** [comment]
Ook op Linux niet (meer)

**Comment by Labhatorian** [comment]
Mac en Linux heeft een ander target waardoor het niet kan pakken

**Comment by usadson** [comment]
target wordt geüpdatet door refreshWP() maar de target in PopUp verandert niet. nu opgelost.
